AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: propagate-cfn-tags
    Description: Propagates CloudFormation's stack tags to resources that are currently not propagated automatically - e.g. CloudWatch Logs.
    Author: Lumigo
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['lambda', 'cloudformation', 'tags', 'devops']
    HomePageUrl: https://github.com/lumigo-io/SAR-Propagate-CFN-Tags.git
    SemanticVersion: 1.9.0
    SourceCodeUrl: https://github.com/lumigo-io/SAR-Propagate-CFN-Tags.git

Globals:
  Function:
    Runtime: nodejs10.x
    MemorySize: 128
    Environment:
      Variables:
        LOG_LEVEL: INFO

Resources:
  Propagate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/propagate.handler
      Timeout: 60
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackResources
              - logs:ListTagsLogGroup
              - logs:TagLogGroup
              - logs:UntagLogGroup
              - states:ListTagsForResource
              - states:TagResource
              - states:UntagResource
            Resource: "*"
      Events:
        CloudFormationEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.cloudformation
              detail-type:
                - AWS API Call via CloudTrail
              detail:
                eventSource:
                  - cloudformation.amazonaws.com
                eventName:
                  - CreateStack
                  - UpdateStack

  PropagateLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Propagate}

  PropagateAll:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/propagate-all.handler
      Timeout: 840
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - cloudformation:ListStacks
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackResources
              - logs:ListTagsLogGroup
              - logs:TagLogGroup
              - logs:UntagLogGroup
              - states:ListTagsForResource
              - states:TagResource
              - states:UntagResource
            Resource: "*"

  PropagateAllLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PropagateAll}

  LambdaInvocationCustomResource:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:374852340823:applications/lambda-invocation-cfn-custom-resource
        SemanticVersion: 1.4.0

  # custom resource to invoke the PropagateAll function during deployment
  InvokePropagateAll:
    Type: Custom::LambdaInvocation
    DependsOn:
      - PropagateAll
      - LambdaInvocationCustomResource
    Properties:
      ServiceToken: !GetAtt LambdaInvocationCustomResource.Outputs.FunctionArn
      FunctionName: !Ref PropagateAll
      Payload: {}
